// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "configuration" {
  type = object({
    dev_login  = bool
    public_url = optional(string)
    google_oauth = optional(object({
      client_id     = optional(string)
      client_secret = optional(string)
    }))
    github_oauth = optional(object({
      client_id     = optional(string)
      client_secret = optional(string)
    }))
  })
}
variable "database" {
  type = object({
    database            = string
    host                = string
    identifier          = optional(string)
    logical_replication = optional(bool)
    major_version       = string
    password            = string
    port                = number
    region              = optional(string)
    security_group_id   = optional(string)
    username            = string
  })
}
variable "image" {
  type = object({
    repository = string
    tag        = string
  })
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "replicas" {
  type = number
}
variable "resources" {
  type = object({
    cpu    = string
    memory = string
  })
}
variable "runtime" {
  type = object({
    authentication = object({
      cluster = object({
        certificate-authority-data = string
        server                     = string
      })
      user = object({
        token = string
      })
    })
    namespace = optional(string)
  })
}
